import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { CatalystInstaller } from '@catalyst-monitor/nextjs/server'
import styles from './layout.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CatalystInstaller />
        <div className={styles.layoutContent}>
          <Link className={styles.home} href="/">
            Go Home
          </Link>
          <div className={styles.contentWrapper}>{children}</div>
        </div>
      </body>
    </html>
  )
}
